import getplayers,getmatchids,getchampiondata,gettraitdata,getitemdata,getcompdata,getotherdata,getpopularitydata
import sqlite3
from datetime import datetime

if __name__ == '__main__':
    a = datetime.now()
    getplayers.get_all_masters()
    getmatchids.get_all_match_ids()
    db = sqlite3.connect("databases/match_ids.sqlite")
    im = db.cursor()
    im.execute("CREATE TABLE IF NOT EXISTS temp_table as SELECT DISTINCT * FROM match_ids;")
    im.execute("DELETE FROM match_ids;")
    im.execute("INSERT INTO match_ids SELECT * FROM temp_table")
    db.commit()
    im.close()
    getchampiondata.get_all_champ_data()
    getchampiondata.parse_all_champ_data()
    gettraitdata.get_all_trait_data()
    gettraitdata.parse_all_trait_data()
    getitemdata.get_item_data()
    getitemdata.parse_all_item_data()
    getcompdata.get_all_comp_data()
    getpopularitydata.getchampscore()
    getpopularitydata.getchampdiff()
    getpopularitydata.gettraitscore()
    getpopularitydata.gettraitdiff()
    getpopularitydata.getitemscore()
    getpopularitydata.getitemdiff()
    getotherdata.get_last_update()
    getotherdata.get_total_matches()
    b = datetime.now()
    print('total',b-a)